[package]
name = "stronghold_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota_stronghold = "0.4.1"
riker = "0.4.2"
actix = "0.12.0"
